# Generated by Django 5.2.7 on 2026-03-25 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('dispositivos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusOrdenDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'estatus_orden_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='TipoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'tipo_comentario',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente')),
            ],
            options={
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='OrdenDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_soporte', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software')], max_length=8)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dispositivos.dispositivo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.orden')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipo_dispositivo')),
            ],
            options={
                'db_table': 'orden_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='HistorialOrdenDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.estatusordendispositivo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.tecnico')),
                ('orden_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordendispositivo')),
            ],
            options={
                'db_table': 'historial_orden_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tecnico')),
                ('orden_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordendispositivo')),
                ('tipo_comentario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.tipocomentario')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.AddConstraint(
            model_name='ordendispositivo',
            constraint=models.UniqueConstraint(fields=('orden', 'dispositivo'), name='unique_orden_dispositivo'),
        ),
        migrations.AddIndex(
            model_name='historialordendispositivo',
            index=models.Index(fields=['estatus', 'fecha_fin'], name='historial_o_estatus_574338_idx'),
        ),
    ]
