# Generated by Django 5.2.8 on 2026-03-25 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_email_alter_cliente_id_cliente_and_more'),
        ('ordenes', '0002_alter_orden_codigo_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='codigo_seguimiento',
            field=models.CharField(db_column='codigoSeguimiento', default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_orden',
            field=models.AutoField(db_column='idOrden', primary_key=True, serialize=False),
        ),
    ]
