# Generated by Django 5.2.8 on 2026-03-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_dispositivo_cliente'),
        ('ordenes', '0003_alter_orden_cliente_alter_orden_codigo_seguimiento_and_more'),
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='dispositivo',
            field=models.ForeignKey(blank=True, db_column='idDispositivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='dispositivos.dispositivo'),
        ),
        migrations.AddField(
            model_name='orden',
            name='estatus',
            field=models.ForeignKey(blank=True, db_column='idEstatusOrdenDispositivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='seguimiento.estatusordendispositivo'),
        ),
    ]
