# Generated by Django 5.2.7 on 2026-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('telefonoAlternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True)),
            ],
            options={
                'db_table': 'CLIENTE',
            },
        ),
    ]
