# Generated by Django 5.2.8 on 2026-03-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(db_column='idCliente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(db_column='nombreCompleto', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(db_column='telefono', db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_alternativo',
            field=models.CharField(blank=True, db_column='telefonoAlternativo', max_length=20, null=True),
        ),
    ]
