# Generated by Django 5.2.8 on 2026-03-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0002_alter_dispositivo_id_dispositivo_and_more'),
        ('ordenes', '0003_alter_orden_cliente_alter_orden_codigo_seguimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusOrdenDispositivo',
            fields=[
                ('id_estatus', models.AutoField(db_column='idEstatusOrdenDispositivo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'estatus_orden_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='OrdenDispositivo',
            fields=[
                ('id_orden_dispositivo', models.AutoField(db_column='idOrdenDispositivo', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='fechaInicio', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='fechaFin', null=True)),
                ('id_tipo_soporte', models.PositiveSmallIntegerField(blank=True, db_column='idTipoSoporte', null=True)),
                ('id_tipo_dispositivo', models.PositiveSmallIntegerField(blank=True, db_column='idTipoDispositivo', null=True)),
                ('dispositivo', models.ForeignKey(db_column='idDispositivo', on_delete=django.db.models.deletion.PROTECT, related_name='orden_dispositivos', to='dispositivos.dispositivo')),
                ('orden', models.ForeignKey(db_column='idOrden', on_delete=django.db.models.deletion.CASCADE, related_name='orden_dispositivos', to='ordenes.orden')),
            ],
            options={
                'db_table': 'orden_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='HistorialOrdenDispositivo',
            fields=[
                ('id_historial', models.AutoField(db_column='idHistorial', primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(db_column='fechaAsignacion')),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='fechaFin', null=True)),
                ('id_tecnico', models.PositiveSmallIntegerField(db_column='idTecnico')),
                ('id_estatus', models.ForeignKey(db_column='idEstatusOrdenDispositivo', on_delete=django.db.models.deletion.PROTECT, related_name='historials', to='seguimiento.estatusordendispositivo')),
                ('id_orden_dispositivo', models.ForeignKey(db_column='idOrdenDispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='historials', to='seguimiento.ordendispositivo')),
            ],
            options={
                'db_table': 'historial_orden_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(db_column='idComentario', primary_key=True, serialize=False)),
                ('comentario', models.TextField(db_column='comentario')),
                ('fecha_creacion', models.DateTimeField(db_column='fechaCreacion')),
                ('id_tecnico', models.PositiveSmallIntegerField(blank=True, db_column='idTecnico', null=True)),
                ('id_tipo_comentario', models.PositiveSmallIntegerField(db_column='idTipoComentario')),
                ('orden_dispositivo', models.ForeignKey(db_column='idOrdenDispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='seguimiento.ordendispositivo')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.AddIndex(
            model_name='ordendispositivo',
            index=models.Index(fields=['orden'], name='idx_ord_orden'),
        ),
        migrations.AddIndex(
            model_name='ordendispositivo',
            index=models.Index(fields=['dispositivo'], name='idx_ord_dispositivo'),
        ),
        migrations.AddIndex(
            model_name='ordendispositivo',
            index=models.Index(fields=['fecha_fin'], name='idx_ord_fechaFin'),
        ),
        migrations.AddIndex(
            model_name='historialordendispositivo',
            index=models.Index(fields=['id_tecnico'], name='idx_hist_idTec'),
        ),
        migrations.AddIndex(
            model_name='historialordendispositivo',
            index=models.Index(fields=['id_estatus', 'fecha_fin'], name='idx_hist_est_f'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['orden_dispositivo'], name='idx_com_orden'),
        ),
    ]
