# Generated by Django 5.2.7 on 2026-02-24 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('usuarios', '0002_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico_Tipo_Especializacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_soporte', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('AMBOS', 'Ambos')], max_length=10)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especializaciones', to='usuarios.tecnico')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipo_dispositivo')),
            ],
            options={
                'unique_together': {('tecnico', 'tipo_dispositivo', 'tipo_soporte')},
            },
        ),
    ]
