# Generated by Django 5.2.8 on 2026-03-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='id_dispositivo',
            field=models.AutoField(db_column='idDispositivo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marca',
            name='id_marca',
            field=models.AutoField(db_column='idMarca', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=30, unique=True),
        ),
    ]
