# Generated by Django 5.2.8 on 2026-03-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_email_alter_cliente_id_cliente_and_more'),
        ('dispositivos', '0002_alter_dispositivo_id_dispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='idCliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='clientes.cliente'),
        ),
    ]
